### ISSUE TITLE
Application immediately crashes on Start Up

### ISSUE THREAD

**Issue by ClarenceL** [elastos/Elastos.Trinity#14]
### Steps to Reproduce:

Start Application

### Error Message

`elastOS keeps stopping`

Reported so far on:
- Pixel 4 XL, Android 10
- Samsung S10, Android 10

**Comment by ClarenceL** [comment]
Also please note the testnet APK did work on my phone previously

**Comment by ducaalfa** [comment]
Same problem on huawei p20 pro Android 9. I reinstalled 3 times. Previous update worked.

**Comment by bigp48** [comment]
Sony XZ premium, doesn't load up.

**Comment by OOS-Team** [comment]
Xiaomi Mi a3 
Android 9
Keeps immediately crashing

**Comment by ClarenceL** [comment]
Looks like the issue is with cached/user data - to delete it go to `Apps & app data` under `Storage` and then `Other Apps`, find **ElastOS** and try to `Clear Storage` and `Clear Cache`.

**Comment by ducaalfa** [comment]
Great Clarence, after clearing storage data everything goes smooth !

**Comment by bigp48** [comment]
Tried deleting the cache but still having the same problem with Sony Xz premium.

**Comment by bigp48** [comment]
Mines working now... Thanks

**Comment by ducaalfa** [comment]
> Tried deleting the cache but still having the same problem with Sony Xz premium.

did u delete Storage too  ? Only cache is not enough

**Comment by bigp48** [comment]
> > Tried deleting the cache but still having the same problem with Sony Xz premium.
> 
> did u delete Storage too ? Only cache is not enough

Yes, and it's working now. Thankyou

**Comment by BenjaminPiette** [comment]
Thanks for reporting this issue. Seems like this is related to having a previous APKs installed. We have spotted the bug and made sure we better handle upgrades later on. Now closing this issue. In case you have crashes at start on totally new installations on your devices, that may be a different issue so please feel free to open another github issue with details.
