### ISSUE TITLE
Elastos Schema for credaccess doesn't work with callbackurl

### ISSUE THREAD

**Issue by kpachhai** [elastos/Elastos.Trinity#15]
When trying to use 'elastos://credaccess?Iss=XXX&exp=XXX&callbackurl=XXX&claims=XXX' from an external app(eg. a website), elastOS currently just redirects to a URL with the response instead of data being sent as JSON object to the callback URL. 

This seems to be a bug because callbackurl doesn't seem to work at all in the current version.

**Comment by BenjaminPiette** [comment]
Fixed some time ago.
