### ISSUE TITLE
Clarify Branding

### ISSUE THREAD

**Issue by ghost** [elastos/Elastos.Trinity#21]
* Elastos Trinity
* elastOS Browser

It seems that "elastOS Browser" is the correct one?

> This is the first official release for Trinity, now renamed to elastOS. 

https://play.google.com/store/apps/details?id=org.elastos.trinity.runtime&hl=en

**Comment by jmsaulnier** [comment]
@lazaridiscom I agree, it's very confusing - here https://news.elastos.org/exploring-elastos-what-is-elastos/ it's only `elastOS` but on Play store, it's `elastOS Browser`
Trinity was the codename but all repo are still using it

**Comment by lazaridiscom** [comment]
This needs to be clarified. I avoid chat-channels, possibly someone could ask in the usual chat location.

(as a sidenote: the branding problems occurs in several other locations, too, see e.g.: #14)
