### ISSUE TITLE
iOS Error compilation

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.Trinity#3]
Trying to compile the project following the ReadMe file, I'm getting this issue when compiling with Xcode

`/Elastos.Trinity/Runtime/platform_src/ios/Elastos/Classes/LauncherViewController.swift:73:38: error: use of undeclared type 'AppManagerPlugin'
    @objc func getManagerPlugin() -> AppManagerPlugin {
                                     ^~~~~~~~~~~~~~~~
/Elastos.Trinity/Runtime/platform_src/ios/Elastos/Classes/LauncherViewController.swift:66:45: error: use of undeclared type 'AppManagerPlugin'
                self.basePlugin = value as! AppManagerPlugin;
                                            ^~~~~~~~~~~~~~~~`

**Comment by raozhiming** [comment]
./ToolChain/bin/build all

Is this command executed correctly?

**Comment by jmsaulnier** [comment]
@raozhiming see https://github.com/elastos/Elastos.Trinity/pull/4 dev branch looks unstable for now - works great when checkout / compile from master branch

**Comment by BenjaminPiette** [comment]
We can close this one.
